version: '3.1'

services:
  db:
    container_name: realtor_db
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=realtor
      - POSTGRES_USER=realtor
      - POSTGRES_DB=realtor
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432